VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ILoadCase"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

'' Public properties
Public Property Get Name() As String
End Property
Public Property Let Name(ByVal value As String)
End Property

Public Property Get ID() As Long
End Property
Public Property Let ID(ByVal valus As Long)
End Property


